SELECT H.HACKER_ID, H.NAME, COUNT(C.CHALLENGE_ID) CNUMS
FROM HACKERS H
    JOIN CHALLENGES C ON H.HACKER_ID=C.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME
HAVING CNUMS=(SELECT MAX(CNUMS)
    FROM (SELECT H.HACKER_ID, H.NAME, COUNT(C.CHALLENGE_ID) CNUMS
        FROM HACKERS H JOIN CHALLENGES C ON H.HACKER_ID=C.HACKER_ID
        GROUP BY H.HACKER_ID, H.NAME) AS T1)
    OR CNUMS IN (SELECT T.CNT
    FROM (SELECT COUNT(*) AS CNT
        FROM CHALLENGES
        GROUP BY HACKER_ID) T
    GROUP BY T.CNT
    HAVING COUNT(T.CNT)=1)
ORDER BY CNUMS DESC, H.HACKER_ID;
