SELECT T.HACKER_ID, T.NAME, SUM(MAX_S)
FROM
    (SELECT H.HACKER_ID, H.NAME, S.CHALLENGE_ID, MAX(S.SCORE) MAX_S
    FROM HACKERS H JOIN SUBMISSIONS S ON H.HACKER_ID=S.HACKER_ID
    GROUP BY 1, 2, 3
    HAVING MAX(S.SCORE)>0) AS T
GROUP BY T.HACKER_ID, T.NAME
ORDER BY SUM(MAX_S) DESC, HACKER_ID;