SELECT W.ID, P.AGE, W.COINS_NEEDED, W.POWER
FROM WANDS W JOIN WANDS_PROPERTY P ON W.CODE=P.CODE
    JOIN (SELECT W1.CODE, W1.POWER, MIN(W1.COINS_NEEDED) MINCOINS
    FROM WANDS W1 JOIN WANDS_PROPERTY P1 ON W1.CODE=P1.CODE
    GROUP BY W1.CODE, W1.POWER) T ON W.CODE=T.CODE
WHERE P.IS_EVIL=0 AND W.COINS_NEEDED=T.MINCOINS
ORDER BY W.POWER DESC, P.AGE DESC;